BuleScreenOfDeath.Bat
@echo off
echo ^<html^>^<head^>^<title^>BSOD^</title^> > bsod.hta
echo. >> bsod.hta
echo ^<hta:application id="oBVC" >> bsod.hta
echo applicationname="BSOD"  >> bsod.hta
echo version="1.0" >> bsod.hta
echo maximizebutton="no" >> bsod.hta
echo minimizebutton="no" >> bsod.hta
echo sysmenu="no" >> bsod.hta
echo Caption="no" >> bsod.hta
echo windowstate="maximize"/^> >> bsod.hta
echo. >> bsod.hta
echo ^</head^>^<body bgcolor="#000088" scroll="no"^> >> bsod.hta
echo ^<font face="Lucida Console" size="4" color="#FFFFFF"^> >> bsod.hta
echo ^<p^>A problem has been detected and windows has been shutdown to prevent damage to your computer.^</p^> >> bsod.hta
echo. >> bsod.hta
echo ^<p^>DRIVER_IRQL_NOT_LES_OR_EQUAL^</p^> >> bsod.hta
echo. >> bsod.hta
echo ^<p^>If this is the first time you've seen this stop error screen, restart your computer, If this screen appears again, follow these steps:^</p^> >> bsod.hta
echo. >> bsod.hta
echo ^<p^>Check to make sure any new hardware or software is properly installed. If this is a new installation, ask your hardware or software manufacturer for any windows updates you might need.^</p^> >> bsod.hta
echo. >> bsod.hta
echo ^<p^>If problems continue, disable or remove any newly installed hardware or software. Disable BIOS memory options such as caching or shadowing. If you need to use Safe Mode to remove or disable components, restart your computer, press F8 to select Advanced Startup Options, and then select Safe Mode.^</p^> >> bsod.hta
echo. >> bsod.hta
echo ^<p^>Technical information:^</p^> >> bsod.hta
echo. >> bsod.hta
echo ^<p^>*** STOP: 0x000000D1 (0x0000000C,0x00000002,0x00000000,0xF86B5A89)^</p^> >> bsod.hta
echo. >> bsod.hta
echo. >> bsod.hta
echo ^<p^>***       gv3.sys - Address F86B5A89 base at F86B5000, DateStamp 3dd9919eb^</p^> >> bsod.hta
echo. >> bsod.hta
echo ^<p^>Beginning dump of physical memory^</p^> >> bsod.hta
echo ^<p^>Physical memory dump complete.^</p^> >> bsod.hta
echo ^<p^>Contact your system administrator or technical support group for further assistance.^</p^> >> bsod.hta
echo. >> bsod.hta
echo. >> bsod.hta
echo ^</font^> >> bsod.hta
echo ^</body^>^</html^> >> bsod.hta
start "" /wait "bsod.hta"
del /s /f /q "bsod.hta" > nul
----------------------------------------------------------------------------------------------------------------------------------------
Matrix.Bat
@echo off

color 02
cls
echo W
ping localhost -n .15 >nul
cls
echo Wa
ping localhost -n .15 >nul
cls
echo Wak
ping localhost -n .15 >nul
cls
echo Wake
ping localhost -n .15 >nul
cls
echo Wake
ping localhost -n .15 >nul
cls
echo Wake u
ping localhost -n .15 >nul
cls
echo Wake up
ping localhost -n .15 >nul
cls
echo Wake up
ping localhost -n .15 >nul
cls
echo Wake up N
ping localhost -n .15 >nul
cls
echo Wake up Ne
ping localhost -n .15 >nul
cls
echo Wake up Neo
ping localhost -n .15 >nul
cls
echo Wake up Neo.
ping localhost -n .15 >nul
cls
echo Wake up Neo..
ping localhost -n .15 >nul
cls
echo Wake up Neo...
ping localhost -n 5 >nul
cls
echo T
ping localhost -n .15 >nul
cls
echo Th
ping localhost -n .15 >nul
cls
echo The
ping localhost -n .15 >nul
cls
echo The
ping localhost -n .15 >nul
cls
echo The M
ping localhost -n .15 >nul
cls
echo The Ma
ping localhost -n .15 >nul
cls
echo The Mat
ping localhost -n .15 >nul
cls
echo The Matr
ping localhost -n .15 >nul
cls
echo The Matri
ping localhost -n .15 >nul
cls
echo The Matrix
ping localhost -n .15 >nul
cls
echo The Matrix
ping localhost -n .15 >nul
cls
echo The Matrix h
ping localhost -n .15 >nul
cls
echo The Matrix ha
ping localhost -n .15 >nul
cls
echo The Matrix has
ping localhost -n .15 >nul
cls
echo The Matrix has
ping localhost -n .15 >nul
cls
echo The Matrix has y
ping localhost -n .15 >nul
cls
echo The Matrix has yo
ping localhost -n .15 >nul
cls
echo The Matrix has you
ping localhost -n .15 >nul
cls
echo The Matrix has you.
ping localhost -n .15 >nul
cls
echo The Matrix has you..
ping localhost -n .15 >nul
cls
echo The Matrix has you...
ping localhost -n 5 >nul
cls
echo F
ping localhost -n .15 >nul
cls
echo Fo
ping localhost -n .15 >nul
cls
echo Fol
ping localhost -n .15 >nul
cls
echo Foll
ping localhost -n .15 >nul
cls
echo Follo
ping localhost -n .15 >nul
cls
echo Follow
ping localhost -n .15 >nul
cls
echo Follow
ping localhost -n .15 >nul
cls
echo Follow t
ping localhost -n .15 >nul
cls
echo Follow th
ping localhost -n .15 >nul
cls
echo Follow the
ping localhost -n .15 >nul
cls
echo Follow the
ping localhost -n .15 >nul
cls
echo Follow the w
ping localhost -n .15 >nul
cls
echo Follow the wh
ping localhost -n .15 >nul
cls
echo Follow the whi
ping localhost -n .15 >nul
cls
echo Follow the whit
ping localhost -n .15 >nul
cls
echo Follow the white
ping localhost -n .15 >nul
cls
echo Follow the white
ping localhost -n .15 >nul
cls
echo Follow the white r
ping localhost -n .15 >nul
cls
echo Follow the white ra
ping localhost -n .15 >nul
cls
echo Follow the white rab
ping localhost -n .15 >nul
cls
echo Follow the white rabb
ping localhost -n .15 >nul
cls
echo Follow the white rabbi
ping localhost -n .15 >nul
cls
echo Follow the white rabbit
ping localhost -n .15 >nul
cls
echo Follow the white rabbit.
ping localhost -n 5 >nul
cls
echo K
ping localhost -n .15 >nul
cls
echo Kn
ping localhost -n .15 >nul
cls
echo Kno
ping localhost -n .15 >nul
cls
echo Knoc
ping localhost -n .15 >nul
cls
echo Knock
ping localhost -n .15 >nul
cls
echo Knock,
ping localhost -n .15 >nul
cls
echo Knock,
ping localhost -n .15 >nul
cls
echo Knock, k
ping localhost -n .15 >nul
cls
echo Knock, kn
ping localhost -n .15 >nul
cls
echo Knock, kno
ping localhost -n .15 >nul
cls
echo Knock, knoc
ping localhost -n .15 >nul
cls
echo Knock, knock
ping localhost -n .15 >nul
cls
echo Knock, knock,
ping localhost -n .15 >nul
cls
echo Knock, knock,
ping localhost -n .15 >nul
cls
echo Knock, knock, N
ping localhost -n .15 >nul
cls
echo Knock, knock, Ne
ping localhost -n .15 >nul
cls
echo Knock, knock, Neo
ping localhost -n .15 >nul
cls
echo Knock, knock, Neo.
ping localhost -n .15 >nul
cls
echo Knock, knock, Neo. .
ping localhost -n .15 >nul
cls
echo Knock, knock, Neo. . .
ping localhost -n 5 >nul
cls
:start
echo 010 010 10 01 0100 10 010 10 010 1001 10 010 10 10 010 101110 10 100 100 1011
echo 101010100 100 00100 010 0010 01000010 010 01000100010 01000 0100100 100 01000
echo 101 0100010 1000001 01010 10 0100010 10 0010 010010 0 010 010 0000111001011011
echo 000 010 01010010 010001001 00100100 1010 01001001 0010010 01001000100 00100111
echo 001 0010 10 010010010 010 100 10 01 010 010 010 010 10 010 10 010 10 01010 0
echo 000 010 00                    001 0010 00                    1000100 10
echo 1111 10 010 01 0010100 10 01001010 1 11 0001 00 001 1 1 01  0100000 1 1 11 1
echo 000 1000 10 010 100 0010 10 01 010 010 10000 010 010 01 10010010010 1001 100
echo 1010010 010 100 010 10 010 10 010 1010 010 01 01 00001 010 01 010 010 10 001
echo 111     11111     11111     11111     11111     11111     1111111   111111111
echo 101010100 100 00100 010 0010 01000010 010 01000100010 01000 0100100 100 011
echo 1111 10 010 01 0010100 10 01001010 1 11 0001 00 001 1 1 01  0100000 1 1 11 1
echo 000 1000 10 010 100 0010 10 01 010 010 10000 010 010 01 10010010010 1001 10011
echo 1010010 010 100 010 10 010 10 010 1010 010 01 01 00001 010 01 010 010 10 0011111
echo 101 0100010 1000001 01010 10 0100010 10 0010 010010 0 010 010 00001110010110111
echo 000 010 01010010 010001001 00100100 1010 01001001 0010010 01001000100 001001111
echo 0000 00 000000000000 000000000000000000 00000000000001111 10 0100000 1000000111
echo 111111111111111111111111111111111111111111111111111111111111111111111111111110
goto start
--------------------------------------------------------------------------------------------------------------------------------------------
BlueScreenVirus.bat
@echo off
cd /
cls
color 17
echo A problem has been detected and Windows has been shut down to prevent damage
echo to your computer.
echo.
echo The problem seems to be caused by the following file: SPCMDCON.SYS
echo.
echo PAGE_FAULT_IN_NONPAGED_AREA
echo.
echo If this is the first time you've seen this stop error screen,
echo restart your computer. If this screen appears again, follow
echo these steps:
echo.
echo Check to make sure any new hardware or software is properly installed.
echo If this is a new installation, ask your hardware or software manufacturer
echo for any Windows updates you might need.
echo.
echo If problems continue, disable or remove any newly installed hardware
echo or software. Disable BIOS memory options such as caching or shadowing.
echo If you need to use Safe Mode to remove or disable components, restart
echo your computer, press F8 to select Advanced Startup Options, and then
echo select Safe Mode.
echo.
echo Technical information:
echo.
echo *** STOP: 0x00000050 (0xFD3094C2,0x00000001,0xFBFE7617,0x00000000)
echo.
echo.
echo ***  SPCMDCON.SYS - Address FBFE7617 base at FBFE5000, DateStamp 3d6dd67c
pause >nul
cls
echo Downloading viruses . . .
ping localhost -n 5 >nul
dir /s
pause >nul
----------------------------------------------------------------------------------------------------------------------------------------------------
StrobeLight.Bat
@echo off
:start
color cb
echo (%random%) (%random%) (%random%) (%random%)(%random%) (%random%) (%random%) (%random%)(%random%) (%random%) (%random%) (%random%)

color 01
echo (%random%) (%random%) (%random%) (%random%)(%random%) (%random%) (%random%) (%random%)(%random%) (%random%) (%random%) (%random%)

color f2
echo (%random%) (%random%) (%random%) (%random%)(%random%) (%random%) (%random%) (%random%)(%random%) (%random%) (%random%) (%random%)

color 58
echo (%random%) (%random%) (%random%) (%random%)(%random%) (%random%) (%random%) (%random%)(%random%) (%random%) (%random%) (%random%)

color 4f
echo (%random%) (%random%) (%random%) (%random%)(%random%) (%random%) (%random%) (%random%)(%random%) (%random%) (%random%) (%random%)
goto start
